### ISSUE TITLE
write(bytes[]) sends old bytes

### ISSUE THREAD

**Issue by zyy1251** [aritchie/bluetoothle#200]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] tvOS
 - [] macOS
 - [] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of OS(s) listed above with issue

android 8.0

## Version of Library
6.0.3

## Expected Behaviour
write the exactly bytes I send to the method wirte(byte[])

## Actual Behavior

I use a system timer to send the bytes by 200ms , when I change one of the byte in the byte array,
  write() will send the old bytes a couple times,  when I set the timer to 500ms , wrong times will be less but still here 

## Code of Conduct

                if (writeChar.CanWrite() == true)
                {
                    writeChar.Write(_sendData).Subscribe(async result =>
                    {

                    },
                    exception =>
                    {
                        
                    });
                }

requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
There is an edge case where you can get the wrong callback if you don’t follow certain practices.  It is part of the reason why I hand back a full result.  This is due to the reason that I can’t tag a message Id for android to respond with in its callbacks.  However, it is hard to cause unless you flood the system with entries which in this case is likely for several reasons

1) you aren’t managing the backpressure.  Your timer is going to continue firing even if the previous write is still pending

2) async in the Subscribe is very unrecommended practice.  It only adds to the backpressure from 1.

3) I notice that you seem to be using an instance variable of your send bytes.  Keep in mind Subscribe will fire asynchronously so if your bytes have changed, the comparison is already wrong

**Comment by aritchie** [comment]
To manage flow, you can use SendBlob(stream) which forces an order and flow control

**Comment by zyy1251** [comment]
how I know that the sending is over? and should I just use await writeChar.Write(bytes)? there's less than 30bytes I send once I think 300ms is enough.  not only the result is the old byte , I watched at the device which receive bytes that show it received the old bytes not the new bytes I order to send

**Comment by aritchie** [comment]
You can use await.  The subscribe callback is telling you the send completed, but it is firing that callback asynchronously.  Subscribe is non-blocking.  If you issue a request to send a block of bytes, it will complete in the future even though you've issued other requests.  

You should also note that most BLE drivers on Android only allow 20 byte packets and throw errors when you feed them more. 

I would suggest checking out introtorx.com

**Comment by zyy1251** [comment]
thanks!   I'll try BlobWrite and sending less bytes at once
