### ISSUE TITLE
[Bug] iOS13 Permissions

### ISSUE THREAD

**Issue by simonemarra** [aritchie/bluetoothle#347]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
6.2.6

## Version of OS(s) listed above with issue
iOS 13
Current documentation lacks on new iOS13 Info.plist permission tag needed for Bluetooth.
In fact if the flag
`<key>NSBluetoothAlwaysUsageDescription</key>
<string>YOUR CUSTOM MESSAGE</string>`
is not provided, the app will crash and be closed without any further "try/catch" possibility in C# code.

I made no changes on library code, instead I tested the following scenarios:

## Steps to Reproduce

1. I created a brand new app, let us call it **App#1**, and deployed to a iOS13.1 device (iPhone 8). 
**I did not used the NSBluetoothAlwaysUsageDescription tag on Info.plist**, just like in current documentation. At the same moment the C# code try to access any CrossBleAdapter.Current method the app crashes.

2. I compiled again a previously developed app, let us call it **App#2**, and deployed to a iOS13.1 device (iPhone 8). **This app permissions was accepted using iOS12, before the iOS13 update**
**I did not used the NSBluetoothAlwaysUsageDescription tag on Info.plist**, just like in current documentation. The app in this case works correctly, but the bluetooth permissions were stored on app settings using iOS12, and not using iOS13!

3. I added the **App#1** iOS13 NSBluetoothAlwaysUsageDescription tag
In this case the app permissions are correctly managed and the Ble seems working fine!

## Expected Behavior
Permissions requests managed as it should be

## Actual Behavior
Permissions requests are not fired at all

**Comment by aritchie** [comment]
Unfortunately, there isn't much I can do about this.  I did file a bug with Xamarin since it usually prints things out to the console when these permissions are missing.  I don't think they are going to fix it.  I can only gracefully print out messages before the crash takes place (which I'm doing in the new Shiny.BluetoothLE, but I likely won't bring to this library).  

The docs just need to be updated with the new info.plist entry and the consequences of not entering them.  Feel free to send a PR whenever you find a missing piece of docs
