### ISSUE TITLE
Could not find Windows Runtime type 'Windows.Devices.Bluetooth.BluetoothAdapter'

### ISSUE THREAD

**Issue by AbhijeetChowdhury** [aritchie/bluetoothle#80]
Hi @aritchie ,

I am implementing Plugin.BluetoothLE and I can successfully connect to my BLE devices on Android. But on running the app in UWP it is throwing an exception as "Could not find Windows Runtime type 'Windows.Devices.Bluetooth.BluetoothAdapter". 

Here is my code snippet:

    public void StartBleScanner()
        {
            CrossBleAdapter.Current.Scan().Subscribe(scanresult =>
            {
                if (scanresult.Device.Uuid.ToString("N").Contains("38d269ecde0a"))
                {
                    setProximityValue(scanresult.Rssi);
                }
            });
        }
I am using Visual Studio 2015 on Windows 8.1 to develop my xamarin project.
It is really a great plugin to work with.
Any help on this will be appreciated. Thanks in advance.

**Comment by aritchie** [comment]
@AbhijeetChowdhury this is the second time I've had to ask you to follow the code of conduct.  You would have your answer to this question if you read the readme.  I support the newer version of UWP (windows 10) and even that is considered beta.  I'm only taking PR's for it right now since it still has lots of known issues.

Lastly, please use the issue template (the one you deleted before filing your issue) so that I have all the info I need to answer your question without having to ask every single person that files an issue.
